Update: checkbox & radio
spaceone-dev/spaceone-design-system pull request #299
Opened 2020-12-29 02:59 UTC by danmin20

2020-12-29 03:53 UTC, siyeons commented on molecules/forms/radio/PRadio.vue
> +    const computedClass = computed(() => {
computedClass랑 computedIconClass보다 조금 더 명확한 변수명으로 작성되면 좋을 것 같아요!

2020-12-29 03:56 UTC, siyeons commented on molecules/forms/checkbox/type.ts
> +    error?: boolean;
타입 명세에 오류가 있는 것 같아요. errored로 해야하지않을까요?

2020-12-29 04:12 UTC, yuda110 commented on molecules/forms/radio/PRadio.vue
> +  name: 'PRadio',
저희 인덴트는 다 스페이스 4입니다! 2개 말고 4개로 부탁드려요! :)

2020-12-29 04:19 UTC, WANZARGEN requested changes

2020-12-29 04:19 UTC, WANZARGEN commented on molecules/forms/checkbox/PCheckBox.vue
> +    });
이렇게 되면,  disabled나 error 상태일 때는 text, check-icon 클래스 이름이 없어져서, 기본적으로 가져야할 css 속성을 다 잃어버리게 되는 문제가 있어보여요.

이보다는, 

```html
<template>
    <span class="p-checkbox" :class="{disabled, errored}"
          ...
    >
        ...
            <p-i class="check-icon"
                 ...
            />
       ... 
        <span v-if="$scopedSlots.default" class="text"
              ...
        >
           ...
        </span>
    </span>
</template>
```

위 코드처럼 icon 과 text 에 대하여서는 class 이름을 정적으로 주고, 
동적인 class (disabled, errored) 는 가장 상위 element 하나에만 준 후에,

```css
.p-checkbox {
    .text {
        @apply text-gray-900 cursor-pointer;
        font-weight: 400;
        font-size: 14px;
    }
    .check-icon {
        @apply text-gray-400 cursor-pointer;
    }

    &:hover {
        .text { ... }
        .check-icon { ... }
    }
    .disabled {
        @apply text-gray-400;
        cursor: not-allowed;
        .text { ... }
        .check-icon { ... }
    }
    .errored {
        @apply text-red-500 cursor-pointer;
        .text { ... }
        .check-icon { ... }
    }

   ...

}
```

이런 방식으로 상위 class 이름에 따라 달라지는 부분만 text, check-icon 클래스에 대하여 정의해주는 방식이, 이후에 생길 수 있는 side effect 를 줄이기에 좋아보입니다.

2020-12-29 04:19 UTC, WANZARGEN commented on molecules/forms/checkbox/PCheckBox.vue
>      }
design system 컴포넌트는 재사용시 스타일 변경이 가능하도록 scoped style 을 쓰지 않고 있어요.
따라서 위에서 주입한 slot 이 span 일 경우, 모두 동일하게 해당 style 이 적용될거에요.

최대한 그런 경우를 방지하려면, tag 이름으로 주는 것보다는 .text 처럼 명확한 class 이름으로 스타일을 부여하는게 다양한 경우에 대비하기에 좋으니 위의 코멘트와 겸하여 수정 부탁드립니다. ㅎㅎ

참고로, 해당 css 에서 input 태그는 그냥 태그 명으로 스타일을 적용했는데, checkbox 컴포넌트를 사용할 떄 slot 으로 input 이 들어오는 경우는 해당 컴포넌트를 사용하지 않을 것으로 생각하여, 태그명을 스타일 적용에 쓴 것 같네요 ㅎㅎ

2020-12-29 04:38 UTC, yuda110 commented on molecules/forms/checkbox/PCheckBox.vue
>      }
아 px 단위는 전부 rem으로 바꿔주세요! 웹스톰 플러그인에서 px2rem < 이거 받으심 편하게 수정할 수 있습니다!

2020-12-29 04:39 UTC, WANZARGEN commented on molecules/forms/checkbox/PCheckBox.vue
>  </style>
추가 확인해주실 사항이 있습니다.

1. storybook 으로 확인해보니 hover 상태 css 가 동작을 잘 안하네요..ㅠ 확인 부탁드립니다.
아마도 위에 코멘트 달아놓은 class name 이 사라지는 문제와 관련이 깊어보입니다.

2. errored 에 대한 기획이 우선 명확하지 않아서 헷갈리셨을 것 같아요. 
디자인 파트에 확인 후 이부분은 추가 개발이 필요해보입니다! (이 부분은 다시 다른 채널로 다시말씀 드리겠습니다)

2020-12-29 04:48 UTC, WANZARGEN commented
errored props -> invalid props 로 이름 변경 부탁드립니다.
(다른 컴포넌트들에서 유효하지 않은 입력에 대해서 invalid 라는 이름으로 사용하고 있어서요. ㅎㅎ
의미상으로도 errored 보다는 invalid가 적합해보입니다.)

2021-01-04 06:41 UTC, WANZARGEN commented on molecules/forms/checkbox/PCheckBox.vue
> +            if (props.invalid) return 'invalid check-icon';
textClass, iconClass을 선언하고, 정적인 클래스명과 동적인 클래스명을 같이 리턴하도록 작성하셨네요.

이 경우 로직이 복잡하지 않고 클래스명에 대한 가공이 많지 않으니, template에 클래스명을 직접 바인딩하는게 어떨까요?
한 번 더 타고 들어가는게 가독성을 해치는 것 같아서요.
아래처럼요.

```html
<p-i ...
        :class="{ disabled, invalid }"
        class="check-icon"
        ...
/>
```

또, 동적인 클래스명과 정적인 클래스명을 구분할 수 있어서 더 명확해보여서요.

그런데 이 부분은 순전히 제 생각이라서, 다른분들 의견 궁금합니다.
@yuda110 @siyeons

2021-01-04 06:41 UTC, WANZARGEN commented on molecules/forms/radio/PRadio.vue
> +        });
checkbox 컴포넌트와 동일하게, textClass, iconClass 를 template 직접 바인딩 방식이 어떨까 의견 내봅니다.

2021-01-04 06:46 UTC, siyeons commented on molecules/forms/checkbox/PCheckBox.vue
> +            if (props.invalid) return 'invalid check-icon';
아 이 방식 좋아요! 저희 다른 컴포넌트들이 이렇게 작성되어있어서 이 방향으로 수정되면 좀 통일성이 유지될 것 같아요 ~

2021-01-05 12:04 UTC, WANZARGEN approved these changes

2021-01-05 12:05 UTC, merged