Update PCopyButton
spaceone-dev/spaceone-design-system pull request #357
Opened 2021-01-14 07:07 UTC by danmin20

2021-01-14 08:05 UTC, WANZARGEN requested changes

2021-01-14 08:05 UTC, WANZARGEN commented on src/molecules/buttons/copy-button/PCopyButton.vue
>          }
style 에 태그명 박혀있는거 클래스명 부여해서 변경 부탁드립니다.

2021-01-14 08:05 UTC, WANZARGEN commented on src/molecules/buttons/copy-button/PCopyButton.vue
> +            isMouseOver: false,
isMouseOver 와 같은 이벤트 바인딩을 통한 스타일 부여 방식을 css :hover 방식으로 변경 부탁드립니다.

2021-01-14 08:05 UTC, WANZARGEN commented on src/molecules/buttons/copy-button/PCopyButton.stories.ts
> +            default: select('alertPosition', ['right', 'bottom'], 'right'),
현재 페이지에 alert 토스트가 아래 왼쪽에 위치해야 하는 경우가 있습니다. 추가 부탁드립니다.

2021-01-18 06:21 UTC, yuda110 commented on src/molecules/buttons/copy-button/PCopyButton.vue
>  }
얘네들도 `copy-button-alert`의 클래스인 것 같으니 그 아래 작성하는 게 좋을 것 같습니다!

2021-01-18 06:55 UTC, merged