feat: update functions of disabled prop in PSearchDropdown
spaceone-dev/spaceone-design-system pull request #828
Opened 2022-01-25 08:34 UTC by JeoungSulMo

### To Reviewers
- [ ] Skip

### 작업 분류
- [ ] 신규 기능
- [ ] 버그 수정
- [X] 기능 개선
- [ ] 리팩토링 및 구조 변경
- [ ] 기타

### 작업 상세 내용
#### PSearch
  - Disabled 시 search에서 검색어 입력 뿐만 아니라 hover나 배경색 등 완전한 disabled로 변경되었습니다.
     ![image](https://user-images.githubusercontent.com/50662170/150940615-ffb59e32-583c-453a-b756-383345e4d77f.png)

#### PSearchDropdown
  - Radio button일때, 선택된 값이 태그가 아닌 일반적인 라벨로 표시 되도록 디자인이 바뀌어 수정되었습니다.
     ![image](https://user-images.githubusercontent.com/50662170/150940347-0d0e9900-1edc-4d6f-876a-d1f3fda17d6e.png)

  - Radio 일때의 선택된 값의 형태가 커스텀이 필요한 경우(project tree일 때 group > project의 형태)가 있어 slot으로 뚫었습니다.
  - Disabled 속성 적용시 기능이 변경되었습니다.
      - Disabled: true 일 때
          - Search 불가
          - 드롭다운 메뉴 오픈 불가
          - 태그 삭제 불가
          - Disabled 상태의 css
             ![image](https://user-images.githubusercontent.com/50662170/150940808-0784d869-bc44-4a68-8bd5-3f4cf0ee3da2.png)

### 생각해볼 문제

2022-01-25 08:51 UTC, yuda110 approved these changes
전 좋아보입니다!!!
완진님 리뷰도 받는 게 좋을듯요!

2022-01-25 09:35 UTC, WANZARGEN commented on src/inputs/search/search-dropdown/PSearchDropdown.vue
> +                <p-i ref="tagRef" class="icon" name="ic_delete"
`tagRef` 는 왜 PTag -> PI 로 바인딩 대상이 변경되었나요??

2022-01-25 09:37 UTC, WANZARGEN commented on src/inputs/search/search-dropdown/PSearchDropdown.vue
> +            <div v-if="type === SEARCH_DROPDOWN_TYPE.radioButton &&
p-tag 를 사용하지 않고 왜 자체개발 되었나요?

2022-01-25 09:39 UTC, WANZARGEN requested changes
궁금한 점 코멘트 달았습니다!

2022-01-25 09:40 UTC, WANZARGEN reviewed
피드백 종류 잘못눌러서 다시...

2022-01-25 10:25 UTC, JeoungSulMo commented on src/inputs/search/search-dropdown/PSearchDropdown.vue
> +                <p-i ref="tagRef" class="icon" name="ic_delete"
앗.. div 쪽으로 옮겨야 합니다😭

2022-01-25 10:25 UTC, JeoungSulMo commented on src/inputs/search/search-dropdown/PSearchDropdown.vue
> +            <div v-if="type === SEARCH_DROPDOWN_TYPE.radioButton &&
![image](https://user-images.githubusercontent.com/50662170/150959301-cf0e8ec6-5caa-4848-a758-b4b40602ab55.png)
디자인이 이렇게 바뀌었습니다다!

2022-01-25 10:27 UTC, JeoungSulMo commented on src/inputs/search/search-dropdown/PSearchDropdown.vue
> +            <div v-if="type === SEARCH_DROPDOWN_TYPE.radioButton &&
태그를 사용하지 않고 인풋에 값과 delete버튼으로만 구성되어있어 PTag를 제거했어요!

2022-01-25 11:34 UTC, siyeons commented on src/inputs/search/search-dropdown/PSearchDropdown.vue
> +                <p-i ref="tagRef" class="icon" name="ic_delete"
tag가 삭제되었는데 계속 tagRef<< 로 되어있어서 조금 헷갈리는 것 같아요!!

2022-01-25 11:36 UTC, siyeons reviewed
성모님 눈에 띄게 빠른 성장을 하고 계시네요 👏 요근래 올려주신 코드들 다들 리뷰를 잘 달아주시기도 했지만 저는 성모님이 작성하신 코드 방식이 맘에 들어서 안 단것도있어요 ㅎㅎㅋㅋ 뭔가 헷갈리거나 알아두셨으면 좋은 내용들은 피드백드리도록 할게요!! 열심히 해주셔서 감사합니다~

2022-01-25 11:53 UTC, WANZARGEN commented on src/inputs/search/search-dropdown/PSearchDropdown.vue
> +            <div v-if="type === SEARCH_DROPDOWN_TYPE.radioButton &&
아 요구사항이 바뀐거군요! ㅎㅎ 설명글을 제대로 못봤네요.
감사합니다!

2022-01-26 00:38 UTC, JeoungSulMo commented
감사합니다!! 🙇‍♂️ 🙇‍♂️
변수명이랑  ref 바인딩 수정하였습니다!

2022-01-26 00:39 UTC, merged

2022-01-26 00:45 UTC, admin-spaceone commented
:tada: This PR is included in version 1.1.0-beta.231 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@spaceone/design-system/v/1.1.0-beta.231)
- [GitHub release](https://github.com/spaceone-dev/spaceone-design-system/releases/tag/v1.1.0-beta.231)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: