fix: hide treemap label if the value is 5 or less
spaceone-dev/spaceone-design-system pull request #891
Opened 2022-03-10 23:34 UTC by yuda110

## To Reviewers
- [ ] Skipping reviews is not a problem

## Type of Change
- [ ] New feature
- [x] Bug fixes
- [ ] Feature improvement
  - [ ] These changes require a usage change
- [ ] Others (performance improvement, refactoring, CI/CD, etc.)

## Description
Hide label text of Treemap if the value is 5 or less

Before / After
![스크린샷 2022-03-11 오전 8 23 07](https://user-images.githubusercontent.com/18563857/157772044-e7fed38f-13d5-4d59-a1af-4a17fd16cc0e.png) ![스크린샷 2022-03-11 오전 8 22 24](https://user-images.githubusercontent.com/18563857/157772072-f2a43689-7511-4ffc-871a-f056c344ba81.png)

## Things to Talk About
Because of the ratio calculation, `totalValue` is added as an argument to `drawTreemapChart()`.
```typescript
// before
drawTreemapChart(chart, props.nameOptions, props.valueOptions);

//after
const totalValue = sum(state.filteredData.map(d => d.value));
drawTreemapChart(chart, props.nameOptions, props.valueOptions, totalValue);
```

or, we can get labelBullet from `drawTreemapChart()` and calculate it in `drawChart()`.
```typescript
const totalValue = sum(state.filteredData.map(d => d.value));
const [series, labelBullet] = drawTreemapChart(chart, props.nameOptions, props.valueOptions, totalValue);
labelBullet.label.adapter.add('text', .....
```

2022-03-11 04:38 UTC, WANZARGEN requested changes
I commented on something that could cause a critical issue. 
Please check it.

2022-03-11 04:38 UTC, WANZARGEN commented on src/data-display/dynamic/dynamic-chart/templates/treemap/index.vue
> +            const totalValue = sum(state.filteredData.map(d => d.value));
This component doesn't know what key the value is in.
The key path information is in `valueOptions` prop.
Also, must defend against the case where the value is `undefined`.

```suggestion
            const totalValue = sum(state.filteredData.map(d => d[props.valueOptions.key] ?? 0));
```

2022-03-11 04:40 UTC, WANZARGEN commented
I prefer first suggestion.
But the problem is, in updating case, this component only change the data. Not the label bullets.
Please check updating case.

2022-03-11 04:43 UTC, yuda110 commented on src/data-display/dynamic/dynamic-chart/templates/treemap/index.vue
> +            const totalValue = sum(state.filteredData.map(d => d.value));
Thanks, I changed the code like that.

2022-03-11 05:01 UTC, yuda110 commented
@WANZARGEN I tested that the label also changes when the data changes.

2022-03-11 09:43 UTC, WANZARGEN approved these changes
Looks good to me :)

2022-03-14 01:08 UTC, merged

2022-03-14 01:13 UTC, admin-spaceone commented
:tada: This PR is included in version 1.1.0-beta.263 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@spaceone/design-system/v/1.1.0-beta.263)
- [GitHub release](https://github.com/spaceone-dev/spaceone-design-system/releases/tag/v1.1.0-beta.263)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: